### ISSUE TITLE
Nuage 4.x compatibility

### ISSUE THREAD

**Issue by jmlcv** [nuagenetworks/nuage-openstack-ansible#16]
Hello there! Does the current nuage-openstack-ansible playbooks and roles work with the Nuage VSP 4.x platform?

Best Regards,

José Valente

**Comment by dttocs** [comment]
Yes, they work with OpenStack Liberty, but the wheel packages required to install using them are not released as part of the standard Nuage release, they're a special request item.  You can ask your Nokia/Nuage contact for them, and they'll need to contact me (scottd@nuagenetworks.net)
